export default [
  {
    name: "vet plus",
    color: "#3C46cc",
    address: "Calle 49 #99-29",
    schedule: "24 Horas",
    img: "./assets/imgs/pet-marker.png",
    description: "Cuidados Veterinarios",
    phone_number: "6103104",
    rate: 0,
    distance: null,
    heading: null,
    latlng: { lat: 4.687484, lng: -74.0784845 },
    categories: ["consulta veterinaria", "urgencias"],
    services: [
      "exámenes diagnósticos",
      "médicos especialistas",
      "urgencias",
      "cirugías",
      "vacunación",
      "hospitalización",
      "procedimientos",
      "terapias",
      "consultas",
      "odontología"
    ]
  },
  {
    name: "clínica dover s.a.s",
    color: "#3C46cc",
    address: "Calle 126a #7-98, Bogotá",
    schedule: "24 Horas",
    img: "./assets/imgs/pet-marker.png",
    description: "Veterinario",
    phone_number: "516-9500",
    website: "dover.com.co",
    rate: 4.5,
    latlng: { lat: 4.7017656, lng: -74.0320396 },
    categories: ["consulta veterinaria", "urgencias"],
    services: [
      "consulta especializada",
      "odontología",
      "etología",
      "rehabilitación",
      "electrocardiografía",
      "electroencefalografía",
      "imágenes diagnostica",
      "uci - unidad de cuidados intensivos"
    ]
  },
  {
    name: "dover pet center",
    color: "#3C46cc",
    address: "Cra. 7 a #126 A - 31, Bogotá",
    schedule: "lunes a sabado 8:00am-19:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "tienda de productos para mascotas",
    phone_number: "612-8699",
    website: "dover.com.co",
    rate: 0,
    latlng: { lat: 4.7017361, lng: -74.0322143 },
    categories: ["peluqueria", "hotel", "colegio", "pet shop"],
    services: ["belleza", "hotel y colegio", "servicio funerarios", "certificados y asesorías para viaje", "microchip e identificación"]
  },
  {
    name: "dover colina",
    color: "#3C46cc",
    address: "Carrera 58 # 137 A – 16 bogota ",
    schedule: "lunes a sabado 8:00am-18:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "tienda de productos para mascotas",
    phone_number: "520-5879",
    website: "dover.com.co",
    rate: 4.8,
    latlng: { lat: 4.7269897, lng: -74.0826546 },
    categories: ["consulta veterinaria"],
    services: ["consulta general", "vacunación", "cirugía", "hospitalización", "laboratorio clínico", "anestesia"]
  },
  {
    name: "animals center boyaca",
    color: "#3C46cc",
    address: "Av Boyaca #64-79 Bogota",
    schedule: "lunes a sabado 9:00am -20:00pm, domingo 9:00am-18:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "2233205/4907586/2246560",
    website: "",
    rate: 3.8,
    latlng: { lat: 4.6780421, lng: -74.1041223 },
    categories: ["consulta veterinaria", "guarderia", "farmacia", "peluqueria"],
    services: ["consulta general", "guarderia", "cirugía", "medicamentos", "laboratorio clínico", "odontologia", "sala de belleza"]
  },
  {
    name: "animals center",
    color: "#3C46cc",
    address: "cr 50 #22-45 sur bogota",
    schedule: "lunes a sabado 9:00am -19:00pm, domingo 9:00am-18:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "7201529/7202980",
    website: "",
    rate: 4.0,
    latlng: { lat: 4.60337, lng: -74.1560699 },
    categories: ["consulta veterinaria", "guarderia", "farmacia", "peluqueria"],
    services: ["consulta general", "guarderia", "cirugía", "medicamentos", "laboratorio clínico", "odontologia", "sala de belleza"]
  },
  {
    name: "tu hospital veterinario",
    color: "#3C46cc",
    address: "av caracas #58-05 bogota",
    schedule: "",
    img: "./assets/imgs/pet-marker.png",
    description: "hospital Veterinario",
    phone_number: "",
    website: "",
    rate: 4.4,
    latlng: { lat: 4.6447761, lng: -74.0678458 },
    categories: ["consulta veterinaria", "urgencias"],
    services: ["consulta general", "hospitalizacion", "rayos x", "ecografia", "urgencias 24 horas"]
  },
  {
    name: "zoovida",
    color: "#3C46cc",
    address: "calle 103 #14-76",
    schedule: "24 Horas",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "6349224",
    website: "zoovida.com.co",
    rate: 2.2,
    latlng: { lat: 4.6875666, lng: -74.0484776 },
    categories: ["consulta veterinaria", "farmacia", "peluqueria", "pet shop", "urgencias"],
    services: [
      "hospitallizacion",
      "laboratorio clinico",
      "farmacia",
      "peluqueria",
      "pet shop",
      "imagenologia",
      "medicina prepagada",
      "urgencias"
    ]
  },
  {
    name: "zoovet",
    color: "#3C46cc",
    address: "Ac 3 #38b-35",
    schedule: "lunes a sabado 9:00-7:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "medico",
    phone_number: "5603040",
    website: "zoovetclinicaveterinaria.com",
    rate: 0,
    latlng: { lat: 4.6103274, lng: -74.1118773 },
    categories: ["consulta veterinaria", "farmacia", "peluqueria", "pet shop", "guarderia", "urgencias"],
    services: [
      "consulta general",
      "laboratorio clinico",
      "farmacia",
      "peluqueria",
      "pet shop",
      "guarderia",
      "hospitalizacion",
      "urgencias",
      "vacunacion",
      "cirugias",
      "imagenologia",
      "odontologia"
    ]
  },
  {
    name: "animal medical care",
    color: "#3C46cc",
    address: "avenida 9 #117a-51",
    schedule: "24 horas",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "2154324/3108569509",
    website: "",
    rate: 4.7,
    latlng: { lat: 4.695431, lng: -74.0363667 },
    categories: ["consulta veterinaria", "urgencias"],
    services: ["consulta general", "ortopedia", "hospitalizacion", "urgencias", "imagenologia", "laboratorio clinico"]
  },
  {
    name: "animal health neurology",
    color: "#3C46cc",
    address: "cra 70 #54-63",
    schedule: "lunes a sabado 8:00am-17:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "hospital veterinario",
    phone_number: "6599125",
    website: "",
    rate: 4.2,
    latlng: { lat: 4.6695955, lng: -74.1049645 },
    categories: ["consulta veterinaria", "urgencias"],
    services: ["consulta general", "laboratorio clinico", "consulta especializada", "vacunacion", "ortopedia", "urgencias", "cirugias"]
  },
  {
    name: "clini sur",
    color: "#3C46cc",
    address: "av caracas #20-45 sur bogota",
    schedule: "lunes a sabado 8:00am-19:00pm, domingo 8:00am-16:30pm",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "2094601/3102226096",
    website: "clinisur.org",
    rate: 3.8,
    latlng: { lat: 4.581972, lng: -74.1038337 },
    categories: ["consulta veterinaria", "pet shop", "guarderia"],
    services: [
      "consulta general",
      "laboratorio clinico",
      "endoscopia",
      "odontologia",
      "radiologia",
      "urgencias",
      "hospitalizacion",
      "cirugias",
      "pet shop",
      "guarderia"
    ]
  },
  {
    name: "animal bull",
    color: "#3C46cc",
    address: " 64A #50b-34",
    schedule: "lunes a sabado 9:00am-19:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "4663063/3124490939",
    website: "www.animalbull.co",
    rate: 4.3,
    latlng: { lat: 4.6610386, lng: -74.082249 },
    categories: ["consulta veterinaria", "pet shop", "guarderia", "farmacia", "peluqueria", "urgencias"],
    services: [
      "consulta general",
      "laboratorio clinico",
      "vacunacion",
      "odontologia",
      "rayos x",
      "urgencias",
      "hospitalizacion",
      "cirugias",
      "pet shop",
      "guarderia",
      "ecografias",
      "ortopedia",
      "cardiologia",
      "farmacia",
      "peluqueria"
    ]
  },
  {
    name: "veterinaria cpvet",
    color: "#3C46cc",
    address: "cll 75 #100-05 bogota",
    schedule: "lunes a domingo 9:00am-21:00pm",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "8037853",
    website: "cpvet.co",
    rate: 4.9,
    latlng: { lat: 4.7061406, lng: -74.1168668 },
    categories: ["consulta veterinaria", "guarderia"],
    services: ["consulta general", "laboratorio clinico", "vacunacion", "cirugias", "imagenologia", "guarderia"]
  },
  {
    name: "nefrovet",
    color: "#3C46cc",
    address: "cll 134 #17-58 bogota",
    schedule: "",
    img: "./assets/imgs/pet-marker.png",
    description: "veterinario",
    phone_number: "",
    website: "",
    rate: 5.0,
    latlng: { lat: 4.717447, lng: -74.0487776 },
    categories: ["consulta veterinaria", "guarderia", "farmacia"],
    services: ["consulta general", "laboratorio clinico", "vacunacion", "cirugias", "imagenologia", "guarderia", "farmacia"]
  },
  {
    name: "orthovet clinica veterinaria",
    color: "#3C46cc",
    address: "crra 50 #119-11 bogota",
    schedule: "",
    img: "./assets/imgs/pet-marker.png",
    description: "hospital veterinario",
    phone_number: "2151533",
    website: "orthovet.com.co",
    rate: 4.8,
    latlng: { lat: 4.7020318, lng: -74.0614594 },
    categories: ["consulta veterinaria", "guarderia"],
    services: ["consulta general", "laboratorio clinico", "vacunacion", "cirugias", "imagenologia", "guarderia", "consulta especializada"]
  },
  {
    name: "TheCamPets",
    color: "#3C46cc",
    address: "Calle 172 # 24 ",
    schedule: "",
    img: "./assets/imgs/pet-marker.png",
    description: "escuela",
    phone_number: "3102684430",
    rate: 4,
    latlng: { lat: 4.778067, lng: -74.0934617 },
    categories: ["urgencias", "hotel", "colegio", "peluqueria"],
    services: [
      "transporte puerta a puerta",
      "hotel",
      "colegio",
      "peluquería",
      "adiestramiento",
      "asistencia médicas",
      "emergencias",
      "consulta general",
      "recreación",
      "guarderia"
    ]
  },
  {
    name: "Agrocampo",
    color: "#3C46cc",
    address: "Calle 73 # 20-62 ",
    schedule:
      " Lunes 7: 30am a 19:00 pm Martes 7: 30am a 19: 00pm Miércoles 7: 30am a 19: 00pm Jueves  7: 30am a 19: 00pm Viernes 7: 30am a 19: 00pm Sábados 7: 30 a 19: 30 Domingos cerrado  ",
    img: "./assets/imgs/pet-marker.png",
    description: "tienda de alimentos para animales",
    phone_number: "3265999",
    rate: 4,
    latlng: { lat: 4.6618217, lng: -74.0641853 },
    categories: ["pet shop", "farmacia"],
    services: ["farmacia", "pet shop"]
  },
  {
    name: "Ceba Mascotas",
    color: "#3C46cc",
    address: "72 A AK # 14-47 ",
    schedule:
      "Lunes 7:30am a 07:30pm Martes 07:30am a 07:30pm, Miércoles 07:30am a 07:30pm, Jueves 07:30am a 07:30 pm Viernes 07:30am a 07:30pm Sábados 07:30am a 08:00pm Domingos cerrado ",
    img: "./assets/imgs/pet-marker.png",
    description: "tienda de productos para mascotas",
    phone_number: "3269500",
    rate: 4,
    latlng: { lat: 4.6608237, lng: -74.0640519 },
    categories: ["pet shop", "farmacia"],
    services: ["farmacia", "pet shop"]
  },
  {
    name: "La Res Clinica Veterinaria",
    color: "#3C46cc",
    address: " Autopista Nte # 106 b - 66 ",
    schedule:
      " Lunes  8:00am a 07:00pm Martes 8:00am a 07: 00pm Miercoles 8:00am a 07: 00pm Jueves 8:00am a 07: 00pm Viernes 8:00am a 07: 00pm Sábado 8:00am a 07: 00pm Domingos cerrado  ",
    img: "./assets/imgs/pet-marker.png",
    description: "tienda de productos para mascotas",
    phone_number: "3269500",
    rate: 4,
    latlng: { lat: 4.6952561, lng: 74.0640143 },
    categories: ["pet shop", "farmacia"],
    services: [" farmacia", "pet shop", "consulta general", " consultas especializadas", "ortopedia", "cardiología", "homeopatía"]
  },
  {
    name: "Puppy Export Tienda Para Mascotas Sede Sur",
    color: "#3C46cc",
    address: "calle 38 a sur # 34 a - 04 ",
    schedule:
      "Lunes 8:00am a 08:00pm Martes 8: 00am a 08: 00pm Miercoles 8: 00am a 08: 00pm Jueves 8: 00am a 08: 00pm Viernes 8: 00am a 08: 00pm Sábado 8: 00am a 08: 00pm Domingo 8: 00am a 08: 00pm ",
    img: "./assets/imgs/pet-marker.png",
    description: "tienda de productos para mascotas",
    phone_number: "4660989",
    rate: 4,
    latlng: { lat: 4.5942799, lng: -74.1387244 },
    categories: ["pet shop", "peluqueria", "consulta veterinaria"],
    services: ["pet shop", "tienda", "concentrados", "peluquería", "consulta veterinaria", "criadero de cachorros"]
  },
  {
    name: "Puppy Land Colombia",
    color: "#3C46cc",
    address: "calle 61 b  # 4 b este - 1 a  4b este - 83  ",
    schedule: "abierto las 24 horas ",
    img: "./assets/imgs/pet-marker.png",
    description: "guardería canina",
    phone_number: "3115170330",
    rate: 5,
    latlng: { lat: 4.6413318, lng: 74.0791579 },
    categories: ["guardería", "peluqueria", "hotel", "consulta veterinaria"],
    services: ["peluquería", "consulta veterinaria", "guardería", "hotel"]
  }
];
